"""Sample catalog data for the book recommendation system."""

from __future__ import annotations

SAMPLE_BOOKS = [
    {
        "title": "三体",
        "author": "刘慈欣",
        "category": "科幻",
        "description": "地球文明与三体文明跨越时空的碰撞史诗，兼具硬核科学设定与宏大哲思。",
        "cover_url": "https://images.unsplash.com/photo-1512820790803-83ca734da794",
        "publish_year": 2008,
    },
    {
        "title": "活着",
        "author": "余华",
        "category": "文学",
        "description": "通过福贵跌宕的一生，展现普通人面对命运时的坚韧与悲悯。",
        "cover_url": "https://images.unsplash.com/photo-1495446815901-a7297e633e8d",
        "publish_year": 1993,
    },
    {
        "title": "原则",
        "author": "瑞·达利欧",
        "category": "商业",
        "description": "将生活与工作中的高质量决策拆解为可复用的原则体系。",
        "cover_url": "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f",
        "publish_year": 2017,
    },
    {
        "title": "人类简史",
        "author": "尤瓦尔·赫拉利",
        "category": "历史",
        "description": "从认知革命到科技革命，梳理人类文明发展的关键节点。",
        "cover_url": "https://images.unsplash.com/photo-1476275466078-4007374efbbe",
        "publish_year": 2012,
    },
    {
        "title": "深度学习入门",
        "author": "斋藤康毅",
        "category": "科技",
        "description": "使用直观示例讲解神经网络、反向传播与训练技巧，适合初学者。",
        "cover_url": "https://images.unsplash.com/photo-1481627834876-b7833e8f5570",
        "publish_year": 2016,
    },
    {
        "title": "小王子",
        "author": "圣埃克苏佩里",
        "category": "童话",
        "description": "以童话形式探讨爱、责任与成长，语言简洁却富有哲理。",
        "cover_url": "https://images.unsplash.com/photo-1455885666463-9c47cb5fc4ca",
        "publish_year": 1943,
    },
    {
        "title": "嫌疑人X的献身",
        "author": "东野圭吾",
        "category": "悬疑",
        "description": "一场看似完美的谋划与天才侦探之间的心理博弈。",
        "cover_url": "https://images.unsplash.com/photo-1519681393784-d120267933ba",
        "publish_year": 2005,
    },
    {
        "title": "纳瓦尔宝典",
        "author": "埃里克·乔根森",
        "category": "成长",
        "description": "围绕财富与幸福，提供可实践的思维模型与行动框架。",
        "cover_url": "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0",
        "publish_year": 2020,
    },
    {
        "title": "被讨厌的勇气",
        "author": "岸见一郎",
        "category": "心理",
        "description": "通过青年与哲人的对话，阐释阿德勒心理学中的课题分离与自由。",
        "cover_url": "https://images.unsplash.com/photo-1473755504818-b72b6dfdc226",
        "publish_year": 2013,
    },
    {
        "title": "明朝那些事儿",
        "author": "当年明月",
        "category": "历史",
        "description": "用通俗幽默的方式讲述明朝历史人物与事件。",
        "cover_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c",
        "publish_year": 2006,
    },
    {
        "title": "解忧杂货店",
        "author": "东野圭吾",
        "category": "文学",
        "description": "跨越时空的书信往来，治愈不同人生困境。",
        "cover_url": "https://images.unsplash.com/photo-1474932430478-367dbb6832c1",
        "publish_year": 2012,
    },
    {
        "title": "代码整洁之道",
        "author": "Robert C. Martin",
        "category": "科技",
        "description": "讲解可维护代码的核心原则，强调命名、函数与重构实践。",
        "cover_url": "https://images.unsplash.com/photo-1519389950473-47ba0277781c",
        "publish_year": 2008,
    },
]

# Synthetic user ratings used to bootstrap collaborative filtering.
# (username, book_title, rating)
BOOTSTRAP_RATINGS = [
    ("alice", "三体", 5),
    ("alice", "深度学习入门", 4),
    ("alice", "代码整洁之道", 5),
    ("alice", "原则", 4),
    ("bob", "活着", 5),
    ("bob", "解忧杂货店", 4),
    ("bob", "被讨厌的勇气", 4),
    ("bob", "小王子", 4),
    ("charlie", "嫌疑人X的献身", 5),
    ("charlie", "解忧杂货店", 5),
    ("charlie", "三体", 3),
    ("charlie", "明朝那些事儿", 4),
    ("diana", "人类简史", 5),
    ("diana", "明朝那些事儿", 4),
    ("diana", "原则", 4),
    ("diana", "纳瓦尔宝典", 5),
    ("eric", "三体", 5),
    ("eric", "人类简史", 4),
    ("eric", "嫌疑人X的献身", 4),
    ("eric", "小王子", 3),
]
